[[rules]]
rules = [
  "DOMAIN-SUFFIX,google.com,PROXY,force-remote-dns",
  "IP-CIDR,10.0.0.0/8,DIRECT",
  "IP-CIDR,127.0.0.0/8,DIRECT",
  "IP-CIDR,172.16.0.0/12,DIRECT",
  "IP-CIDR,192.168.0.0/16,DIRECT"
]